export const tableProAccoData = {
  tableData: [
    {
      product: 'KLONDIKE nano Full Synthetic EP-1.5',
      packageSize: 'Jug: 5 L / 1.32 GAL',
      part: 'KL-LD4660 ',
      perCase: '2',
      perPallet: '56',
      unitPrice: '$4,501.40',
      hoverButton: 'ADD TO CART',
      productImage: '/static/images/productImage.png',
    },
    {
      product: ' ISO 220 EP Full Synthetic',
      packageSize: 'Dru:208 L/55.48 GAL',
      part: 'KL-LD4690',
      perCase: '3',
      perPallet: '4',
      unitPrice: '$3.80',
      hoverButton: 'ADD TO CART',
      productImage: '/static/images/productImage.png',
    },
    {
      product: 'ISO 680 EP Full Synthetic',
      packageSize: 'Tote: 1000 L / 275',
      part: 'KL-LD4695',
      perCase: '6',
      perPallet: '56',
      unitPrice: '$109.10',
      hoverButton: 'ADD TO CART',
      productImage: '/static/images/productImage.png',
    },
    {
      product: '0W-20 API SP/GF-6A dexos1® Full Synthetic',
      packageSize: 'Bulk:',
      part: 'KL-LD4699',
      perCase: '0',
      perPallet: '18',
      unitPrice: '$81.84',
      hoverButton: 'ADD TO CART',
      productImage: '/static/images/productImage.png',
    },
  ],
}
